spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: msp
    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/msp?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  thymeleaf:
    cache: true
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    encoding: UTF-8
demo:
  name: test131
  file: wode
